---

- name: Create and Deploy Ambari Blueprint
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
  - name: Send Blueprint
    shell: 'curl -H "X-Requested-By: ambari" -X POST -u admin:admin http://184.94.253.77:8080/api/v1/blueprints/single-node-hdp-cluster -d @cluster_configuration2.json'

  - name: Register and Deploy Blueprint
    shell: 'curl -H "X-Requested-By: ambari" -X POST -u admin:admin http://184.94.253.77:8080/api/v1/clusters/HDP -d @hostmapping2.json'

