---

- name: Create a Hortonworks Ambari deployment
  hosts: localhost
  vars_files:
    - vars.yaml

- name: Configure Hadoop + Yarn + Map Reduce
  become: true
  hosts: ambari-master
  tasks:

  - name: Change to HDFS
    shell: sudo su - hdfs
  - name: Make directory for Cloud
    shell: hadoop fs -mkdir /user/cloud
  - name: Add permissions for Cloud
    shell: hadoop fs -chown cloud:cloud /user/cloud
  - name: exit to cloud user
    shell: exit



  - name: Upload Constitution.txt to hadoop
    shell: hadoop fs -put /home/cloud/hadoop-ops-course/data/constitution.txt
  - name: Run Yarn + Map Reduce Client
    become_user: cloud
    shell: yarn jar /usr/hdp/current/hadoop-mapreduce-client/hadoop-mapreduce-examples.jar wordcount constitution.txt wordcount_output4
  
  - name: Review word count
    become_user: cloud
    shell: hadoop fs -cat wordcount_output4/part-r-00000 > wordcount.txt
  - name: display wordcount.txt
    shell: more wordcount.txt
    register: shell_output2
  - debug: msg="{{ shell_output2.stdout_lines }}"



